-- Alter table to add new optional columns
ALTER TABLE "technical_visit_reports"
ADD COLUMN "market_name" VARCHAR(100),
ADD COLUMN "site_address" VARCHAR(500),
ADD COLUMN "whatsapp_no" VARCHAR(20),
ADD COLUMN "visit_category" VARCHAR(50),
ADD COLUMN "customer_type" VARCHAR(50),
ADD COLUMN "const_area_sq_ft" INTEGER,
ADD COLUMN "current_brand_price" DECIMAL(10, 2),
ADD COLUMN "site_stock" DECIMAL(10, 2),
ADD COLUMN "est_requirement" DECIMAL(10, 2),
ADD COLUMN "supplying_dealer_name" VARCHAR(255),
ADD COLUMN "nearby_dealer_name" VARCHAR(255),
ADD COLUMN "is_converted" BOOLEAN,
ADD COLUMN "conversion_type" VARCHAR(50),
ADD COLUMN "is_tech_service" BOOLEAN,
ADD COLUMN "service_desc" VARCHAR(500),
ADD COLUMN "influencer_name" VARCHAR(255),
ADD COLUMN "influencer_phone" VARCHAR(20),
ADD COLUMN "is_scheme_enrolled" BOOLEAN,
ADD COLUMN "influencer_productivity" VARCHAR(100);